# Miniconda stuff shamelessly copied from
# https://gist.github.com/dan-blanchard/7045057
# and
# https://github.com/Jorge-C/ordination/blob/master/.travis.yml
language: python
python:
  - 2.7
# Need to set this so that packages installed with apt-get are available
virtualenv:
  system_site_packages: true
env:
    global:
        secure: cXRXecOJ0LpQBPfl/CvrrvuDTQpN0zZ1mpGG4rs02yWRmRoykqzJpPNHBHZ1MWEHGwOP9QqXjuPTRPEHYBP4I9V/7uHgrd4rIg50gonyr0LdQFLL9QxsM6SMH/zHyma+hpWmg2k3ad6zBd0GFkaACtVlS/x2F8JG+W6TrU/oL+I=
before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-2.2.2-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/anaconda/bin:$PATH
    # Update conda itself
    - conda update --yes conda
    - conda install --yes pip python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib nose sphinx imaging ipython numba pep8==1.6.2 six
    - pip install coverage==3.7.1 coveralls==0.5 sphinx_bootstrap_theme==0.4.5
install:
    - python setup.py build
    - pip install .
    - make clean && python setup.py build_ext --inplace
script:
    - make test
    - make coverage
    - make clean; cd doc; make html && cd ..
after_success:
    - coveralls
    - bash .push-docs.sh
after_failure:
    - make pep8
